version: "3"

services:

  server:
    restart: always
    build: .
    command: python -O server.py
    # network_mode: "host"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    extra_hosts:
      - "grpc-on-206:127.0.0.1"
    networks:
      - proxy
  
networks:
  proxy: