# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scan.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nscan.proto\"\xc3\x01\n\rScanParameter\x12\x10\n\x08scan_mod\x18\x01 \x01(\t\x12\x17\n\x0fscan_host_range\x18\x02 \x01(\t\x12\x16\n\x0escan_host_port\x18\x03 \x01(\t\x12\x19\n\x11scan_host_exclude\x18\x04 \x01(\t\x12\x12\n\nscan_speed\x18\x05 \x01(\t\x12\x12\n\nscan_delay\x18\x06 \x01(\t\x12\x19\n\x11scan_host_timeout\x18\x07 \x01(\t\x12\x11\n\tscan_args\x18\x08 \x01(\t\"-\n\nScanResult\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x13\n\x0bscan_result\x18\x02 \x01(\t\"(\n\nHostConfig\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"v\n\nSNMPConfig\x12\x16\n\x0eread_community\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x17\n\x0fmax_repetitions\x18\x03 \x01(\x05\x12\x19\n\x11\x63onvert_to_string\x18\x04 \x01(\x08\x12\x0b\n\x03oid\x18\x05 \x01(\t\"d\n\x0b\x42\x61seRequest\x12\x11\n\tscan_type\x18\x01 \x01(\t\x12 \n\x0bhost_config\x18\x02 \x01(\x0b\x32\x0b.HostConfig\x12 \n\x0bsnmp_config\x18\x03 \x01(\x0b\x32\x0b.SNMPConfig\"z\n\x0eScanSNMPConfig\x12\x16\n\x0eread_community\x18\x01 \x03(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x17\n\x0fmax_repetitions\x18\x03 \x01(\x05\x12\x19\n\x11\x63onvert_to_string\x18\x04 \x01(\x08\x12\x0b\n\x03oid\x18\x05 \x01(\t\"C\n\x0eScanNMAPConfig\x12\x0f\n\x07network\x18\x01 \x03(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x12\n\nscan_spend\x18\x03 \x01(\t\"u\n\x0f\x44iscoverRequest\x12\x16\n\x0eupdate_dynamic\x18\x01 \x01(\x08\x12$\n\x0bnmap_config\x18\x02 \x01(\x0b\x32\x0f.ScanNMAPConfig\x12$\n\x0bsnmp_config\x18\x03 \x01(\x0b\x32\x0f.ScanSNMPConfig\"?\n\x0cSNMPResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x03 \x01(\t26\n\x0bScanService\x12\'\n\x04Scan\x12\x0e.ScanParameter\x1a\x0b.ScanResult\"\x00\x30\x01\x32\x63\n\x0bSNMPService\x12%\n\x04\x42\x61se\x12\x0c.BaseRequest\x1a\r.SNMPResponse\"\x00\x12-\n\x08\x44iscover\x12\x10.DiscoverRequest\x1a\r.SNMPResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scan_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCANPARAMETER._serialized_start=15
  _SCANPARAMETER._serialized_end=210
  _SCANRESULT._serialized_start=212
  _SCANRESULT._serialized_end=257
  _HOSTCONFIG._serialized_start=259
  _HOSTCONFIG._serialized_end=299
  _SNMPCONFIG._serialized_start=301
  _SNMPCONFIG._serialized_end=419
  _BASEREQUEST._serialized_start=421
  _BASEREQUEST._serialized_end=521
  _SCANSNMPCONFIG._serialized_start=523
  _SCANSNMPCONFIG._serialized_end=645
  _SCANNMAPCONFIG._serialized_start=647
  _SCANNMAPCONFIG._serialized_end=714
  _DISCOVERREQUEST._serialized_start=716
  _DISCOVERREQUEST._serialized_end=833
  _SNMPRESPONSE._serialized_start=835
  _SNMPRESPONSE._serialized_end=898
  _SCANSERVICE._serialized_start=900
  _SCANSERVICE._serialized_end=954
  _SNMPSERVICE._serialized_start=956
  _SNMPSERVICE._serialized_end=1055
# @@protoc_insertion_point(module_scope)
